
package org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.annotations.ASN1Module;



        @ASN1Module ( name = "TEST_ASN", isImplicitTags =  true  ) 
        public class TEST_ASN {
        }
        