
package org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.CoderFactory;
import org.bn.annotations.ASN1BoxedType;
import org.bn.annotations.ASN1Element;
import org.bn.annotations.ASN1PreparedElement;
import org.bn.coders.IASN1PreparedElement;
import org.bn.coders.IASN1PreparedElementData;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "TestTParent2" )
    public class TestTParent2 implements IASN1PreparedElement {
                
        
        @ASN1Element ( name = "TestTParent2", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
        private TestParent2  value;        

        
        
        public TestTParent2 () {
        }
        
        
        
        public void setValue(TestParent2 value) {
            this.value = value;
        }
        
        
        
        public TestParent2 getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(TestTParent2.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            