
package org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.CoderFactory;
import org.bn.annotations.ASN1Element;
import org.bn.annotations.ASN1PreparedElement;
import org.bn.annotations.ASN1Sequence;
import org.bn.annotations.ASN1SequenceOf;
import org.bn.annotations.ASN1String;
import org.bn.coders.IASN1PreparedElement;
import org.bn.coders.IASN1PreparedElementData;
import org.bn.coders.UniversalTag;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "ValueWithParams", isSet = false )
    public class ValueWithParams implements IASN1PreparedElement {
            
    @ASN1String( name = "", 
        stringType =  UniversalTag.PrintableString , isUCS = false )
    
        @ASN1Element ( name = "value", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private String value = null;
                
  
@ASN1SequenceOf( name = "params", isSetOf = false ) 

    
        @ASN1Element ( name = "params", isOptional =  true , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private java.util.Collection<PlainParamsMap>  params = null;
                
  
        
        public String getValue () {
            return this.value;
        }

        

        public void setValue (String value) {
            this.value = value;
        }
        
  
        
        public java.util.Collection<PlainParamsMap>  getParams () {
            return this.params;
        }

        
        public boolean isParamsPresent () {
            return this.params != null;
        }
        

        public void setParams (java.util.Collection<PlainParamsMap>  value) {
            this.params = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ValueWithParams.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            